---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: strong-skink
spec:
  project: default
  source:
    path: charts/grafana
    repoURL: https://github.com/f5-rahm/techxchange-gitops-lab.git
    targetRevision: HEAD
  destination:
    namespace: strong-skink
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
